pull_request_rules:
  - name: automatic merge dependabot
    conditions:
      - author=dependabot[bot]
    actions:
      merge:
        method: rebase
        rebase_fallback: squash

  - name: approve dependabot
    conditions:
      - author=dependabot[bot]
    actions:
      review:
        type: APPROVE

  - name: automatic merge repomanager
    conditions:
      - author=the-repository-manager[bot]
    actions:
      merge:
        method: rebase
        rebase_fallback: squash

  - name: approve repomanager
    conditions:
      - author=the-repository-manager[bot]
    actions:
      review:
        message: auto approve repomanager

  - name: assign to owner
    conditions:
      - check-failure>1
    actions:
      assign:
        users:
          - chrisns
